#!/bin/bash
## TODO: Update DNS to non-botnet dns provider
docker-machine create \
               -d virtualbox\
               --virtualbox-cpu-count 2\
               --virtualbox-memory 4096\
               --engine-opt dns=8.8.8.8\
               --engine-insecure-registry d.h:5000\
               default
docker-machine ssh default 'sudo sh -c "echo 127.0.0.1 d.h >> /etc/hosts"'
