#!/bin/bash
docker-compose run web rails new . --force --database=postgresql --skip-bundle

## Creates a new Rails project
## Need to update the permissions afterwards with `chown -R $USER:$USER .`
## Essentially just DL's remote deps and sets up project for lcl running

# user  ☆  ~/code/htmldrum/docker/docker-compose/rails[master ?] $ ./build
# Building web...
# Step 1 : FROM ruby:2.2.0
#  ---> ac90cee00759
# Step 2 : RUN apt-get update -qq && apt-get install -y build-essential libpq-dev
#  ---> Using cache
#  ---> 77bccd52f400
# Step 3 : RUN mkdir /myapp
#  ---> Using cache
#  ---> bf1e4c95e695
# Step 4 : WORKDIR /myapp
#  ---> Using cache
#  ---> 4d65d33954b1
# Step 5 : ADD Gemfile /myapp/Gemfile
#  ---> Using cache
#  ---> 43cef04c3ff2
# Step 6 : ADD Gemfile.lock /myapp/Gemfile.lock
#  ---> Using cache
#  ---> 9db0e86afeb7
# Step 7 : RUN bundle install
#  ---> Running in 807b24d81f8c
# Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
# installing your bundle as root will break this application for all non-root
# users on this machine.
# Fetching gem metadata from https://rubygems.org/...........
# Fetching additional metadata from https://rubygems.org/..
# Resolving dependencies...
# Installing rake 10.5.0
# Installing i18n 0.7.0
# Installing json 1.8.3
# Installing minitest 5.8.4
# Installing thread_safe 0.3.5
# Installing tzinfo 1.2.2
# Installing activesupport 4.2.5.1
# Installing builder 3.2.2
# Installing erubis 2.7.0
# Installing mini_portile2 2.0.0
# Installing nokogiri 1.6.7.2
# Installing rails-deprecated_sanitizer 1.0.3
# Installing rails-dom-testing 1.0.7
# Installing loofah 2.0.3
# Installing rails-html-sanitizer 1.0.3
# Installing actionview 4.2.5.1
# Installing rack 1.6.4
# Installing rack-test 0.6.3
# Installing actionpack 4.2.5.1
# Installing globalid 0.3.6
# Installing activejob 4.2.5.1
# Installing mime-types 2.99
# Installing mail 2.6.3
# Installing actionmailer 4.2.5.1
# Installing activemodel 4.2.5.1
# Installing arel 6.0.3
# Installing activerecord 4.2.5.1
# Using bundler 1.7.12
# Installing concurrent-ruby 1.0.0
# Installing thor 0.19.1
# Installing railties 4.2.5.1
# Installing sprockets 3.5.2
# Installing sprockets-rails 3.0.1
# Installing rails 4.2.5.1
# Your bundle is complete!
# It was installed into /usr/local/bundle
#  ---> 6cc05d4cf019
# Removing intermediate container 807b24d81f8c
# Step 8 : ADD . /myapp
#  ---> 0ecdfe31c9cf
# Removing intermediate container d2f6f14fb2dd
# Successfully built 0ecdfe31c9cf
#        exist
#       create  README.rdoc
#       create  Rakefile
#       create  config.ru
#       create  .gitignore
#        force  Gemfile
#       create  app
#       create  app/assets/javascripts/application.js
#       create  app/assets/stylesheets/application.css
#       create  app/controllers/application_controller.rb
#       create  app/helpers/application_helper.rb
#       create  app/views/layouts/application.html.erb
#       create  app/assets/images/.keep
#       create  app/mailers/.keep
#       create  app/models/.keep
#       create  app/controllers/concerns/.keep
#       create  app/models/concerns/.keep
#       create  bin
#       create  bin/bundle
#       create  bin/rails
#       create  bin/rake
#       create  bin/setup
#       create  config
#       create  config/routes.rb
#       create  config/application.rb
#       create  config/environment.rb
#       create  config/secrets.yml
#       create  config/environments
#       create  config/environments/development.rb
#       create  config/environments/production.rb
#       create  config/environments/test.rb
#       create  config/initializers
#       create  config/initializers/assets.rb
#       create  config/initializers/backtrace_silencers.rb
#       create  config/initializers/cookies_serializer.rb
#       create  config/initializers/filter_parameter_logging.rb
#       create  config/initializers/inflections.rb
#       create  config/initializers/mime_types.rb
#       create  config/initializers/session_store.rb
#       create  config/initializers/wrap_parameters.rb
#       create  config/locales
#       create  config/locales/en.yml
#       create  config/boot.rb
#       create  config/database.yml
#       create  db
#       create  db/seeds.rb
#       create  lib
#       create  lib/tasks
#       create  lib/tasks/.keep
#       create  lib/assets
#       create  lib/assets/.keep
#       create  log
#       create  log/.keep
#       create  public
#       create  public/404.html
#       create  public/422.html
#       create  public/500.html
#       create  public/favicon.ico
#       create  public/robots.txt
#       create  test/fixtures
#       create  test/fixtures/.keep
#       create  test/controllers
#       create  test/controllers/.keep
#       create  test/mailers
#       create  test/mailers/.keep
#       create  test/models
#       create  test/models/.keep
#       create  test/helpers
#       create  test/helpers/.keep
#       create  test/integration
#       create  test/integration/.keep
#       create  test/test_helper.rb
#       create  tmp/cache
#       create  tmp/cache/assets
#       create  vendor/assets/javascripts
#       create  vendor/assets/javascripts/.keep
#       create  vendor/assets/stylesheets
#       create  vendor/assets/stylesheets/.keep
